version: 0.2

env:
  #StartNumber：開始通し番号
  #InstanceNumber：インスタンス作成数
  #AMI_ID：起動するAMIのID
  #InstanceType：起動するインスタンスタイプ
   variables:
    Start_Nunmber: "value"
    Instance_Number: "value"
    AMI_ID: "value"
    InstanceType: "value"
phases:
   install:
     commands:
       - echo install aws cli v2
       - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
       - unzip awscliv2.zip
       - ./aws/install --bin-dir /root/.pyenv/shims --install-dir /usr/local/aws-cli --update
   pre_build:
     commands:
       - END_CNT=$((Start_Nunmber -1 + Instance_Number))
   build:
     commands:
       - echo ${AMI_ID}
       - sh create_stack.sh ${Start_Nunmber} ${END_CNT} ${AMI_ID} ${InstanceType}
   post_build:
     commands:
       - echo Build completed on date