Parameters:
    InstanceName:
        Description: "InstanceName"
        Type: String
        Default: ""
    AMIID:
        Description: "AMI_ID"
        Type: String
        Default: ""
    InstanceType:
        Description: "InstanceType"
        Type: String
        Default: ""
Resources:
    EC2: 
        Type: AWS::EC2::Instance
        Properties: 
            ImageId: !Ref AMIID
            KeyName: test-key
            InstanceType: !Ref InstanceType
            SecurityGroupIds:
                - sg-08a6848144065c5aa
            SubnetId: subnet-0ba8ccc922f32a172
            Monitoring: true
            Tags:
                - Key: Name
                  Value: !Ref InstanceName
                - Key: Type
                  Value: Production-BULL-KPI
            BlockDeviceMappings: 
                - DeviceName: "/dev/xvda"
                  Ebs: 
                    DeleteOnTermination: "false"
                    VolumeSize: "8"
                    VolumeType: gp2
            IamInstanceProfile: !Ref InstanceProfile
    InstanceProfile:
        Type: AWS::IAM::InstanceProfile
        Properties:
            Path: /
            Roles: 
            - "2022lambda"